// DEMO DATA — not real inventory.
//
// Used only when the catalogue request comes back empty, which is what happens
// whenever the backend is not running. It exists so the section can be shown
// and reviewed without the API up; the moment /product returns anything, real
// products replace all of this and none of it renders.
//
// The prices, ratings and review counts below are invented. The images are
// not — they are real Cloudinary ids from the product manifest, so the cards
// look like the real thing rather than grey boxes.
//
// To retire this: delete the file and the DEMO_PRODUCTS fallback in
// RecommendedSection.jsx. Nothing else references it.
export const DEMO_PRODUCTS = [
    {
        _id: 'demo-iphone-14-pro',
        productName: 'iPhone 14 Pro · Unlocked',
        grade: 'Good',
        storage: '256 GB',
        color: { name: 'Deep Purple' },
        price: 744,
        originalPrice: 823,
        reviewScore: 4.4,
        peopleReviewed: 1489,
        outOfStock: false,
        linkTo: '/shop?category=iPhone&model=iPhone%20Pro',
        image: 'upcell/products/iphone/iphone-14-pro-deep-purple-ab38596d4a--0dada363',
    },
    {
        _id: 'demo-iphone-15-plus',
        productName: 'iPhone 15 Plus · Unlocked',
        grade: 'Excellent',
        storage: '128 GB',
        color: { name: 'Blue' },
        price: 706,
        originalPrice: 763.4,
        reviewScore: 4.5,
        peopleReviewed: 1494,
        outOfStock: false,
        linkTo: '/shop?category=iPhone&model=iPhone%20Plus',
        image: 'upcell/products/iphone/iphone-14-plus-blue-e7f73732d8--b5ba7a6e',
    },
    {
        _id: 'demo-ipad-mini',
        productName: 'iPad mini (7th gen)',
        grade: 'Premium',
        storage: '64 GB',
        color: { name: 'Blue' },
        price: 364,
        originalPrice: 399,
        reviewScore: 4.4,
        peopleReviewed: 466,
        outOfStock: false,
        linkTo: '/shop?category=iPad&model=iPad%20mini',
        image: 'upcell/products/ipad/ipad-mini-7th-gen-blue-61qza-d1jcl-ac--3e09eb2b',
    },
    {
        _id: 'demo-macbook-air-m1',
        productName: 'MacBook Air 13" M1',
        grade: 'Good',
        storage: '256 GB',
        color: { name: 'Silver' },
        price: 529,
        originalPrice: 612,
        reviewScore: 4.6,
        peopleReviewed: 980,
        outOfStock: false,
        linkTo: '/shop?category=MacBook&model=MacBook%20Air',
        image: 'upcell/products/macbook/macbook-air-13-m1-silver-2-55576b3889--cf41d438',
    },
    {
        _id: 'demo-iphone-13',
        productName: 'iPhone 13 · Unlocked',
        grade: 'Fair',
        storage: '128 GB',
        color: { name: 'Blue' },
        price: 329,
        originalPrice: 362.07,
        reviewScore: 4.3,
        peopleReviewed: 1502,
        outOfStock: false,
        linkTo: '/shop?category=iPhone&model=iPhone',
        image: 'upcell/products/iphone/iphone-13-base-variant-blue-59d0ab89c7--fc480107',
    },
    {
        _id: 'demo-ipad-air',
        productName: 'iPad Air (4th gen)',
        grade: 'Good',
        storage: '64 GB',
        color: { name: 'Green' },
        price: 312,
        originalPrice: 349,
        reviewScore: 4.4,
        peopleReviewed: 388,
        outOfStock: false,
        linkTo: '/shop?category=iPad&model=iPad%20Air',
        image: 'upcell/products/ipad/ipad-air-4th-gen-green-71z4o1tak-l-ac--64dc0e79',
    },
    {
        _id: 'demo-macbook-pro-m2',
        productName: 'MacBook Pro 14" M2 Pro',
        grade: 'Excellent',
        storage: '512 GB',
        color: { name: 'Silver' },
        price: 1089,
        originalPrice: 1199,
        reviewScore: 4.7,
        peopleReviewed: 611,
        outOfStock: false,
        linkTo: '/shop?category=MacBook&model=MacBook%20Pro',
        image: 'upcell/products/macbook/macbook-mackbook-pro-m2-13-14-silver-61zsd7--b804f339',
    },
    {
        _id: 'demo-iphone-17-pro-max',
        productName: 'iPhone 17 Pro Max · Unlocked',
        grade: 'Premium',
        storage: '512 GB',
        color: { name: 'Cosmic Orange' },
        price: 1244,
        originalPrice: 1349,
        reviewScore: 4.5,
        peopleReviewed: 210,
        outOfStock: false,
        linkTo: '/shop?category=iPhone&model=iPhone%20Pro%20Max',
        image: 'upcell/products/iphone/iphone-17-pro-max-cosmic-orange-05086f1--20d2d38a',
    },
];
